.PHONY: help

help:
	@echo "Source layout:"
	@echo "  euler_common      - EOS, HLLC, reconstruction, CFL"
	@echo "  flic              - FLIC bundle"
	@echo "  godunov           - Godunov run configs for tasks 2 and 3"
	@echo "  mader_2de         - Mader 2DE code bundle"
	@echo "  simple_piso_pimple, unstructured, mpi_parallel - reserved module folders"
